# -*- coding: utf-8 -*-
"""LISTA03-GO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhNCJNdkEZ-q3gey-vzlMbnsNgCtbgaW
"""

\\Questão 01
package main

import "fmt"

func main() {
    var tmn, busca int
    fmt.Print("Indique o tamanho do vetor: ")
    fmt.Scanln(&tmn)

    Vetor := make([]int, tmn)
    for i := 0; i < tmn; i++ {
        fmt.Scan(&Vetor[i])
    }
    fmt.Print("indique a quantidade de buscas: ")
    fmt.Scanln(&busca)

    for i := 0; i < busca; i++ {
        var nmr int
        fmt.Print("Indique os números à serem buscados: ")
        fmt.Scanln(&nmr)

        enct := false
        for j := 0; j < tmn; j++ {
            if Vetor[j] == nmr {
                enct = true
                break
            }
        }

        if enct {
            fmt.Println("ACHEI")
        } else {
            fmt.Println("NAO ACHEI")
        }
    }
}

\\Questão 02
package main
import "fmt"

func main() {
    var N, K int
    fmt.Print("Indique o tamanho do vetor: ")
    fmt.Scan(&N)

    if N < 1 || N >1000 {
        fmt.Print("Número Inválido")
        fmt.Print("Digite outro número")
        fmt.Scan(&N)
    }

    V:= make([]int, N)
    for i := 0; i < N; i++ {
        fmt.Scan(&V[i])
    }
    fmt.Println("Escreva um número")
    fmt.Scan(&K)

   vetor := 0
    for i := 0; i < len(V); i++ {
    if V[i] >= K {
        vetor++
    }
}

    fmt.Println(vetor)
}

\\Questão 03
package main
import "fmt"

func main() {
    var n int
    fmt.Print("Indique o tamanho do vetor: ")
    fmt.Scan(&n)

    Vetor:= make([]int, n)
    for i := 0; i < n; i++ {
        fmt.Scan(&Vetor[i])
    }
    for i := n-1; i >=0; i-- {
        fmt.Println(Vetor[i])
    }
}

\\Questão 04
package main
import "fmt"

func main() {
    var n int
    fmt.Scan(&n)
    if n >5000 {
       fmt.Println("Número Inválido. Digite outro número")
       fmt.Scan(&n)
    }

       Vetor:= make([]int, n)
    for i := 0; i < n; i++ {
        fmt.Scan(&Vetor[i])
        fmt.Println(Vetor[i])
    }
}

\\ Questão 05
package main
import "fmt"

func main() {
    for {
        var n int
        fmt.Scan(&n)
        if n < 0 || n > 10000 {
       fmt.Println("Número Inválido. Digite outro número")
       fmt.Scan(&n)
        }
        if n == 0 {
                break
            }
       Vetor:= make([]int, n)
       maior := 0
	   posicao := 0
        for i := 0; i < n; i++ {
            fmt.Scan(&Vetor[i])
	        if Vetor[i] > maior {
				maior = Vetor[i]
				posicao = i
	        }
        }
    fmt.Println(maior, posicao)
    }
}

\\Questão 06
package main
import "fmt"

func main() {
        var n, soma int
        fmt.Scan(&n)
        if n > 5000 {
       fmt.Println("Número Inválido. Digite outro número")
       fmt.Scan(&n)
        }
       Vetor := make([]int, n)
        for i := 0; i < n; i++ {
            fmt.Scan(&Vetor[i])
	        soma += Vetor[i]
        }
        fmt.Println(soma)
}

\\Questão 07

\\Questão 08
package main
import "fmt"

func main() {
   var Q, N int
   fmt.Scan(&Q)
    for i :=0; i<=Q; i++ {
        fmt.Scan(&N)
        fmt.Printf("%b",N)
    }

}

\\Questão 09
package main
import "fmt"

func main() {
   var P, x, xb, y, yb, z, zb int
   var ponto float32
   fmt.Scan (&P)
   for i := 0; i <= P; i++ {
       fmt.Scanln(&x, &y, &z)
       fmt.Scanln(&xb, &yb, &zb)
       ponto = math.Sqrt (math.Pow((x-xb),2.0) + math.Pow((y-yb),2.0) + math.Pow((z-zb),2.0))
       fmt.Println("",ponto)
   }

}

\\Questão 10
package main

import "fmt"

func main() {
    var N, unota, mnota, pnota, fnota int
    fmt.Scanln(&N)

    vetor := make([]int, N)
    for i := 0; i < N; i++ {
        fmt.Scanln(&vetor[i])

        if i == N-1 {
            unota = vetor[i]
            fnota++
        }

        if vetor[i] > mnota {
            mnota = vetor[i]
            pnota = i
        }
    }
    for i := 0; i < N-1; i++ {
        if vetor[i] == unota {
            fnota++
        }
    }

    fmt.Println("Nota",unota, "",fnota, "vezes")
    fmt.Println("Nota", mnota, "índice", pnota)
}

\\Questão 11
package main

import "fmt"

func main() {
    var N int
    fmt.Scanln(&N)
    if N > 1000 || N < 1 {
       fmt.Println("Número Inválido. Digite outro número")
       fmt.Scan(&N)
    }

    V := make([]int, N)
    for i := 0; i < N; i++ {
		fmt.Scan(&V[i])
	}
	for i := 0; i < N; i++ {
		fmt.Printf("%d", V[i])
		if i < N-1 {
			fmt.Printf(" ")
		}
	}
	fmt.Println()
	maxV := V[0]
	for i := 1; i < N; i++ {
		if V[i] > maxV {
			maxV = V[i]
		}
	}
	fmt.Println(maxV)

	W := make([]int, N)
	for i := 0; i < N; i++ {
		W[N-i-1] = V[i]
	}
	for i := 0; i < N; i++ {
		fmt.Printf("%d", W[i])
		if i < N-1 {
			fmt.Printf(" ")
		}
	}
	fmt.Println()
	minW := W[0]
	for i := 1; i < N; i++ {
		if W[i] < minW {
			minW = W[i]
		}
	}
	fmt.Println(minW)
}

\\Questão 12
package main

import (
	"fmt"
	"sort"
)

func main() {
	var N int
	fmt.Scanln(&N)
  if N > 1000 || N < 1 {
       fmt.Println("Número Inválido. Digite outro número")
       fmt.Scan(&N)
    }

	lista := make([]int, N)

	for i := 0; i < N; i++ {
		fmt.Scanln(&lista[i])
	}

	sort.Ints(lista)
	for _, ord := range lista {
		fmt.Println(ord)
	}
	fmt.Println()
}

\\Questão 13

\\Questão 14
package main

import
	"fmt"


func main() {
	var N int
	var mediana float32
	fmt.Scanln(&N)

num := make ([]int,N)
    for i := 0; i <= N; i++ {
        fmt.Scanln(num[i])
        if N % 2 =! 0 {
            mediana = i/2
        } if else N % 2 == 0{
            mediana = (i/2+(i/2+1)
        }
    }
    fmt.Println("", mediana)
}

\\Questão 15

\\Questão 16